package server

import (
	"io/fs"
	"os"
	"path/filepath"
	"testing"
)

// TestFrontendSourceGeneratedEmbeddedSync guards the generated/embedded
// frontend contract. Application assets have two copies:
//
//	public/assets/...         canonical maintained assets
//	internal/server/web/...   embedded into the binary (copied from public)
//
// The trees must be exact in both directions, so stale or missing embedded
// files are rejected. HTML remains generated by Nift; CSS and JavaScript are
// maintained directly in public.
func TestFrontendSourceGeneratedEmbeddedSync(t *testing.T) {
	repo, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	generated := filepath.Join(repo, "public")
	embedded := filepath.Join(repo, "internal", "server", "web")

	// Generated and embedded trees must be exact in both directions.
	generatedFiles := map[string]string{}
	if err := filepath.WalkDir(generated, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, _ := filepath.Rel(generated, path)
		b, rerr := os.ReadFile(path)
		if rerr != nil {
			return rerr
		}
		generatedFiles[rel] = string(b)
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	embeddedFiles := map[string]string{}
	if err := filepath.WalkDir(embedded, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, _ := filepath.Rel(embedded, path)
		b, rerr := os.ReadFile(path)
		if rerr != nil {
			return rerr
		}
		embeddedFiles[rel] = string(b)
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	for rel, gen := range generatedFiles {
		emb, ok := embeddedFiles[rel]
		if !ok {
			t.Errorf("generated %s missing in embedded web: run make frontend", rel)
			continue
		}
		if gen != emb {
			t.Errorf("embedded web/%s differs from generated %s: run make frontend", rel, rel)
		}
	}
	for rel := range embeddedFiles {
		if _, ok := generatedFiles[rel]; !ok {
			t.Errorf("stale embedded web/%s has no generated counterpart: run make frontend", rel)
		}
	}
}
